In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("superstore_cleaned.csv")
df.head()

In [12]:
df.shape

(9994, 21)

In [16]:
df["Order Date"] = pd.to_datetime(df["Order Date"], format="%d-%m-%Y")
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="%d-%m-%Y")

In [ ]:
df.info()

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
(df["Profit"] < 0).sum()

np.int64(1871)

In [20]:
df["Discount"].describe()

count    9994.000000
mean        0.156203
std         0.206452
min         0.000000
25%         0.000000
50%         0.200000
75%         0.200000
max         0.800000
Name: Discount, dtype: float64

In [21]:
df[["Sales","Profit"]].describe()

              Sales       Profit
count   9994.000000  9994.000000
mean     229.858001    28.656896
std      623.245101   234.260108
min        0.444000 -6599.978000
25%       17.280000     1.728750
50%       54.490000     8.666500
75%      209.940000    29.364000
max    22638.480000  8399.976000

In [22]:
df["Category"].value_counts()

Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

In [23]:
df["Region"].value_counts()

Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

In [24]:
df["Segment"].value_counts()

Segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64

In [25]:
df[["Sales","Profit"]].sum()

Sales     2.297201e+06
Profit    2.863970e+05
dtype: float64

In [26]:
df.groupby("Category")[["Sales","Profit"]].sum()

                       Sales       Profit
Category
Furniture        741999.7953   18451.2728
Office Supplies  719047.0320  122490.8008
Technology       836154.0330  145454.9481

In [27]:
category_analysis = df.groupby("Category")[["Sales", "Profit"]].sum()

category_analysis["Profit Margin"] = (
    category_analysis["Profit"] / category_analysis["Sales"]
) * 100

category_analysis

                       Sales       Profit  Profit Margin
Category
Furniture        741999.7953   18451.2728       2.486695
Office Supplies  719047.0320  122490.8008      17.035158
Technology       836154.0330  145454.9481      17.395712

In [28]:
monthly_sales = (
    df.groupby(df["Order Date"].dt.to_period("M"))["Sales"]
    .sum()
)

monthly_sales

Order Date
2014-01     14236.8950
2014-02      4519.8920
2014-03     55691.0090
2014-04     28295.3450
2014-05     23648.2870
2014-06     34595.1276
2014-07     33946.3930
2014-08     27909.4685
2014-09     81777.3508
2014-10     31453.3930
2014-11     78628.7167
2014-12     69545.6205
2015-01     18174.0756
2015-02     11951.4110
2015-03     38726.2520
2015-04     34195.2085
2015-05     30131.6865
2015-06     24797.2920
2015-07     28765.3250
2015-08     36898.3322
2015-09     64595.9180
2015-10     31404.9235
2015-11     75972.5635
2015-12     74919.5212
2016-01     18542.4910
2016-02     22978.8150
2016-03     51715.8750
2016-04     38750.0390
2016-05     56987.7280
2016-06     40344.5340
2016-07     39261.9630
2016-08     31115.3743
2016-09     73410.0249
2016-10     59687.7450
2016-11     79411.9658
2016-12     96999.0430
2017-01     43971.3740
2017-02     20301.1334
2017-03     58872.3528
2017-04     36521.5361
2017-05     44261.1102
2017-06     52981.7257
2017-07     45264.4160
2017-08     63120.8880
2017-09     87866.6520
2017-10     77776.9232
2017-11    118447.8250
2017-12     83829.3188
Freq: M, Name: Sales, dtype: float64

In [32]:
monthly_sales.idxmax(),monthly_sales.max()

(Period('2017-11', 'M'), np.float64(118447.825))

In [33]:
monthly_sales.idxmin(),monthly_sales.min()

(Period('2014-02', 'M'), np.float64(4519.892))

In [34]:
region_analysis = df.groupby("Region")[["Sales","Profit"]].sum()
region_analysis

               Sales       Profit
Region
Central  501239.8908   39706.3625
East     678781.2400   91522.7800
South    391721.9050   46749.4303
West     725457.8245  108418.4489

In [35]:
region_analysis.idxmax(),monthly_sales.max()

(Sales     West
 Profit    West
 dtype: str,
 np.float64(118447.825))

In [36]:
region_analysis.idxmin(),monthly_sales.min()

(Sales       South
 Profit    Central
 dtype: str,
 np.float64(4519.892))

In [6]:
top_cust = df.groupby("Customer Name")["Sales"].sum().sort_values(ascending=False).head(10)
top_cust

Customer Name
Sean Miller           25043.050
Tamara Chand          19052.218
Raymond Buch          15117.339
Tom Ashbrook          14595.620
Adrian Barton         14473.571
Ken Lonsdale          14175.229
Sanjit Chand          14142.334
Hunter Lopez          12873.298
Sanjit Engle          12209.438
Christopher Conant    12129.072
Name: Sales, dtype: float64

In [7]:
cust_prof = df.groupby("Customer Name")["Profit"].sum().sort_values(ascending=False).head(10)
cust_prof

Customer Name
Tamara Chand            8981.3239
Raymond Buch            6976.0959
Sanjit Chand            5757.4119
Hunter Lopez            5622.4292
Adrian Barton           5444.8055
Tom Ashbrook            4703.7883
Christopher Martinez    3899.8904
Keith Dawkins           3038.6254
Andy Reiter             2884.6208
Daniel Raglin           2869.0760
Name: Profit, dtype: float64

In [8]:
loss_cust = df.groupby("Customer Name")["Profit"].sum().sort_values().head(10)
loss_cust

Customer Name
Cindy Stewart      -6626.3895
Grant Thornton     -4108.6589
Luke Foster        -3583.9770
Sharelle Roach     -3333.9144
Henry Goldwyn      -2797.9635
Nathan Cano        -2204.8072
Sean Braxton       -2082.7451
Sean Miller        -1980.7393
Christine Phan     -1850.3029
Natalie Fritzler   -1695.9714
Name: Profit, dtype: float64

In [9]:
top_prod = df.groupby("Product Name")["Profit"].sum().sort_values(ascending=False).head(10)
top_prod

Product Name
Canon imageCLASS 2200 Advanced Copier                                          25199.9280
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind     7753.0390
Hewlett Packard LaserJet 3310 Copier                                            6983.8836
Canon PC1060 Personal Laser Copier                                              4570.9347
HP Designjet T520 Inkjet Large Format Printer - 24" Color                       4094.9766
Ativa V4110MDD Micro-Cut Shredder                                               3772.9461
3D Systems Cube Printer, 2nd Generation, Magenta                                3717.9714
Plantronics Savi W720 Multi-Device Wireless Headset System                      3696.2820
Ibico EPK-21 Electric Binding System                                            3345.2823
Zebra ZM400 Thermal Label Printer                                               3343.5360
Name: Profit, dtype: float64

In [10]:
loss_prod = df.groupby("Product Name")["Profit"].sum().sort_values().head(10)
loss_prod

Product Name
Cubify CubeX 3D Printer Double Head Print                           -8879.9704
Lexmark MX611dhe Monochrome Laser Printer                           -4589.9730
Cubify CubeX 3D Printer Triple Head Print                           -3839.9904
Chromcraft Bull-Nose Wood Oval Conference Tables & Bases            -2876.1156
Bush Advantage Collection Racetrack Conference Table                -1934.3976
GBC DocuBind P400 Electric Binding System                           -1878.1662
Cisco TelePresence System EX90 Videoconferencing Unit               -1811.0784
Martin Yale Chadless Opener Electric Letter Opener                  -1299.1836
Balt Solid Wood Round Tables                                        -1201.0581
BoxOffice By Design Rectangular and Half-Moon Meeting Room Tables   -1148.4375
Name: Profit, dtype: float64

In [11]:
discount_analysis = df.groupby("Category")["Discount"].mean().sort_values(ascending=False)
discount_analysis

Category
Furniture          0.173923
Office Supplies    0.157285
Technology         0.132323
Name: Discount, dtype: float64

In [12]:
disc_prof = df.groupby("Discount")["Profit"].agg(["sum","mean","count"])
disc_prof

                  sum        mean  count
Discount
0.00      320987.6032   66.900292   4798
0.10        9029.1770   96.055074     94
0.15        1418.9915   27.288298     52
0.20       90337.3060   24.702572   3657
0.30      -10369.2774  -45.679636    227
0.32       -2391.1377  -88.560656     27
0.40      -23057.0504 -111.927429    206
0.45       -2493.1111 -226.646464     11
0.50      -20506.4281 -310.703456     66
0.60       -5944.6552  -43.077212    138
0.70      -40075.3569  -95.874060    418
0.80      -30539.0392 -101.796797    300

In [14]:
category_disc_analysis = df.groupby(["Category","Discount"])["Profit"].mean()
category_disc_analysis

Category         Discount
Furniture        0.00         69.537173
                 0.10         93.565946
                 0.15         27.288298
                 0.20         10.188535
                 0.30        -48.177103
                 0.32        -88.560656
                 0.40       -215.831957
                 0.45       -226.646464
                 0.50       -238.355537
                 0.60        -43.077212
                 0.70       -259.662627
Office Supplies  0.00         41.708567
                 0.10         67.880050
                 0.20         17.282486
                 0.70        -43.687101
                 0.80       -101.796797
Technology       0.00        158.881657
                 0.10        416.042150
                 0.20         54.735560
                 0.30         65.207900
                 0.40        -52.440104
                 0.50       -636.269092
                 0.70       -851.274743
Name: Profit, dtype: float64

In [16]:
subcategory_analysis = df.groupby("Sub-Category")[["Sales","Profit"]].sum().sort_values("Profit",ascending=False)
subcategory_analysis

                    Sales      Profit
Sub-Category
Copiers       149528.0300  55617.8249
Phones        330007.0540  44515.7306
Accessories   167380.3180  41936.6357
Paper          78479.2060  34053.5693
Binders       203412.7330  30221.7633
Chairs        328449.1030  26590.1663
Storage       223843.6080  21278.8264
Appliances    107532.1610  18138.0054
Furnishings    91705.1640  13059.1436
Envelopes      16476.4020   6964.1767
Art            27118.7920   6527.7870
Labels         12486.3120   5546.2540
Machines      189238.6310   3384.7569
Fasteners       3024.2800    949.5182
Supplies       46673.5380  -1189.0995
Bookcases     114879.9963  -3472.5560
Tables        206965.5320 -17725.4811